### ISSUE TITLE
Summary table not selecting the local species_just global info

### ISSUE THREAD

**Issue by BajaNur** [IsaakBM/AquaMaps_wflow#1]
Hi @IsaakBM 

The script messingaquamaps creates a summary table (speciesInfo_surface.csv) that selects all species rather than just the local ones (in this case was Mediterranean basin).

**Comment by IsaakBM** [comment]
I'm on it. Thanks!

**Comment by IsaakBM** [comment]
Hey @BajaNur 

I just fixed the code and now should give the same summary table for the regions selected. Let me know if that works for you too.

IBM

**Comment by BajaNur** [comment]
Hi @IsaakBM 

Works well, just checked it and now species list matches well.

Thanks,
NAD
